-- Scrap parties master table
CREATE TABLE IF NOT EXISTS scrap_parties (
  id SERIAL PRIMARY KEY,
  party_name VARCHAR(255) UNIQUE NOT NULL,
  address VARCHAR(500) DEFAULT '',
  freight NUMERIC(12, 2) DEFAULT 0,
  opening NUMERIC(14, 2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_scrap_parties_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS scrap_parties_updated_at ON scrap_parties;
CREATE TRIGGER scrap_parties_updated_at
  BEFORE UPDATE ON scrap_parties
  FOR EACH ROW EXECUTE FUNCTION update_scrap_parties_updated_at();

-- Seed data
INSERT INTO scrap_parties (party_name, address, freight, opening) VALUES
  ('Aanish Traders', '', 0, 52000),
  ('Aarush And AbhiShree Supplier', 'Banashthali,Kathmandu', 34195, 0),
  ('Aarvi Packaging Udhyog', '', 0, 105749),
  ('Aavanya Trade & Suppliers Pvt. Ltd.', '', 0, 300000),
  ('Aayush Scrap Pvt Ltd', 'Sitapaila,Kathmandu', 27100, 3150000),
  ('Abhiyan Trading Center Pvt ltd', 'Dhobighat,Lalilpur', 29550, 1715000),
  ('Ahdhari Enterprises Pvt. Ltd', 'Sipadol Suryabinayak Nagarpalika', 22796, 2075000),
  ('Alpha  kawadi supplier', 'Gajuri Nagarpalika-Dhading', 15000, 420000),
  ('Apex Industries', '', 0, 0),
  ('B. K. C. Suppliers', 'Bhaktapur  Nagarpalika', 17100, 85000),
  ('Bageshwori Cartoon Box Udhyog', '', 0, -200000),
  ('Baishanavii Kraft Udhyog', '', 0, 18397609.85),
  ('Baisno Mata Supplier', 'Pokahra ', 14000, 2100000),
  ('Bholenath Enterprises', '', 0, 1650000),
  ('Bikanshika Suppliers Pvt. Ltd.', '', 0, 150000),
  ('Bikram Baba Suppliers Pvt. Ltd.', '', 0, 269855.8),
  ('Binayak Traders & Supplirs', '', 0, 0),
  ('BISHOWKARMA SUPPLIERS', '', 0, 590214.89),
  ('Blue Sky Impex Pvt Ltd', '', 0, 85500),
  ('Danphe Packaging Udhyog', 'Sirutar, Suryabinayak Nagarpalika', 31922, 0),
  ('Fine Corrugation & Coating Industries', '', 0, 0),
  ('GANPATI ELECTRIC & HARDWARE SUPPLIERS', 'Hetauda', 8500, 100000),
  ('Global Carton Udhyog', '', 0, 0),
  ('GOPAL PAPER KABAR', 'Kumhal tole ,Birgunj', 8000, 350000),
  ('Gorkha Brewery Pvt Ltd', '', 0, 0),
  ('Hari Om Suppliers', 'Bharatpur Mahanagarpalika', 12700, 4150000),
  ('Jagdamba Auto Group Pvt. Ltd.', 'Jeetpur,Simara Nagarpalika', 6840, 2542500),
  ('Jaiswal Traders', 'Madhav Narayan Nagarpalika,Rautahat', 11000, 1250000),
  ('Jay  Shiv Shambhoo Cartoon Udhyog', 'Birgunj,Adarshnagar', 5000, 1100000),
  ('Jay Ambe Trade & Suppliers', 'Bharatpur Mahanagarpalika', 11000, 5925000),
  ('Jay Bholenath Cartoon Udhyog', '', 0, 1200000),
  ('Jay Bholenath Traders', 'Chapkaiya,Birgunj', 8500, 3808458.75),
  ('Jay Hanuman Scrap Suppliers', 'Bardibas  Nagarpalika', 11000, 125000),
  ('Jay Hanuman Traders', 'Chandrapur  Nagarpalika', 10500, 550000),
  ('Jay Ma Bhagwati Suppliers', '', 0, 0),
  ('Jay Shree Shambhu Ind', 'Sanepa,Lalitpur', 33025, 2800000),
  ('Jayraj Cartoon Udhyog pvt ltd', '', 0, 0),
  ('Kalika Scrap Suppliers', '', 0, 0),
  ('Kalinichok cartoon tatha plastic udhyog', 'Kageshwori Maohara', 29722, 0),
  ('Kawality Thai Foods Pvt Ltd.', '', 0, 0),
  ('Krishna SAH TRADERS', 'Bateshwor Gaupalika,Janakpur', 13000, 0),
  ('Kwality Oil Refinery Pvt Ltd', '', 0, 0),
  ('L.G. Security Service Private Limited', '', 0, 0),
  ('Lakshay Trading Pvt. Ltd.', 'Chandrapur  Nagarpalika', 10350, 1300000),
  ('Laxmi Ganesh Traders', 'Chandrapur  Nagarpalika', 10350, 250000),
  ('Maheshwor Traders', 'Kalimati Kathmandu', 17500, 0),
  ('Mahi & Rishi Suppliers Pvt Ltd', '', 0, 0),
  ('Malti Scrap Suppliers', '', 0, 0),
  ('Manakamana Kawadi Packaging Udhyog', 'Kageshwori Maohara', 31073, -1436751.7),
  ('Mankamna Iron Scrap Stores', 'Hetauda', 8000, 365000),
  ('Mayur Lamicoats Pvt.Ltd.', '', 0, 0),
  ('MIRMIRE STORE', '', 0, 0),
  ('NAG Traders', '', 0, 35000),
  ('Navdurga Pressing Udhyog', '', 0, 0),
  ('Nepal Trade Link', '', 0, 750000),
  ('New Shree Ramchandra Traders', 'Belahiya-Bhairahwa', 25500, 7675000),
  ('Niranjan Scrap Suppliers', 'New Baneshwor,kathmandu', 22858, 0),
  ('NOBLE PACKAGING PVT LTD', '', 0, 0),
  ('OCB Food & Feeds Pvt.Ltd.', '', 0, 72139.2),
  ('Om Sai Ram Traders', 'Sanepa,Lalitpur', 21835, 6000000),
  ('Omkar Ecopack Pvt Ltd', '', 0, 0),
  ('Pashupati Ceramic pvt ltd', '', 0, 0),
  ('Premia Foods Additives Pvt Ltd', '', 0, 139449.26),
  ('Priyanka Supplier', '', 0, 575000),
  ('Ram Ram Suppliers', 'Vyas Nagarpalika-Damauli', 9900, 170000),
  ('RATANNAGAR  PACKAGING UDHYOG', '', 0, 0),
  ('Ratanshree Packaging Udhyog', '', 0, 0),
  ('Roshani Kawadi Collection', '', 0, 170000),
  ('S R B Suppliers', '', 0, 3250000),
  ('S.M.S. Recycling Pvt. Ltd.', '', 0, 950000),
  ('Sachi jelly udyog', '', 0, 0),
  ('Sah Cartoon Packaging Udhyog', '', 0, 100000),
  ('Sanjay Ajay Stores', '', 0, 61000),
  ('Shiv Stores & Suppliers', '', 0, 30000),
  ('Shivam Packaging Industries (P) Ltd', '', 0, 0),
  ('Shree Basnet Traders', '', 0, 45000),
  ('Shree Ganesh Cartoon Udhyog', '', 0, 0),
  ('Shree Shanichara Suppliers', '', 0, 0),
  ('Siddhi Laxmi Traders', '', 0, 11793518.27),
  ('Speed Exim Pvt Ltd', '', 0, 105000),
  ('Swakriti Recycling Industries Pvt.Ltd', 'Balkot,Suryabinayak ', 24650, 0),
  ('Tirupati Scrap Center', 'Reshamkothi,Birgunj', 0, 0),
  ('Tubby Trading Pvt. Ltd.', 'Kohalpur,Nepalgunj', 35500, 0),
  ('YETI BREWERY LIMITED', '', 0, 1524081.4),
  ('Yeti Distillery Pvt Ltd', '', 0, 1888600),
  ('C.B Traders', '', 0, 20000),
  ('Gress & D.R Supplier', '', 0, 7267.6),
  ('Aarav Traders And Suppliers', '', 0, 19605),
  ('Ankita Scrap', '', 0, 100000),
  ('Annapurna Udhyog', '', 0, 575000),
  ('Ashish Traders', '', 0, 830000),
  ('Bastola Trade Link Pvt. Ltd.', '', 0, 39999.9999999999),
  ('BHAGWATI IRON & CRAFT UDHYOG', '', 0, 139000),
  ('Bhawani Traders & Suppliers', '', 0, 250000),
  ('C.G FOOD (NEPAL) PVT LTD', '', 0, 278780.4),
  ('Govind Traders and Suppliers Pvt. Ltd.', '', 0, 25000),
  ('Himshree Foods Western Nepal Ltd.', '', 0, 181432.25),
  ('Jay Mata Di Scrap & Suppliers', '', 0, 130000),
  ('Laxmi Traders', '', 0, 7000),
  ('Ma Parbati Traders & Suppliers', '', 0, 250000),
  ('Mangalam Industries Ltd', '', 0, 2095.5),
  ('Modern Packaging Industry', '', 0, 2408.6),
  ('Nappy And Paste Materisl Pvt. Ltd.', '', 0, 19255),
  ('Om Shree Shivam Suppliers', '', 0, 28652),
  ('Om Surya Sani Suppliers', '', 0, 29000),
  ('Pashupati Koot Udhyog', '', 0, 461813.4975),
  ('PRINCE TRADERS', '', 0, 175000),
  ('Pritam Stores', '', 0, 350000),
  ('Punj Suppliers', '', 0, 261092.297),
  ('Radhe Radhe Stores', '', 0, 225000),
  ('RAM RAJ KABADI', '', 0, 475401.3),
  ('Ram Scrap Traders', '', 0, 13000),
  ('Saiju Enterprises', '', 0, 21305.65),
  ('Saipal Business House Pvt Ltd', '', 0, 50000),
  ('Salomsha Kawadi Suppliers', '', 0, 51000),
  ('Sandesh Scrap Center', '', 0, 830000),
  ('Shivam Sungaram Kabad Centre', '', 0, 25000),
  ('Siddhartha Oil Industries', '', 0, 157541.9),
  ('SITAL  ENTERPRIESES', '', 0, 285500),
  ('R.P. KUSHWAHA SUPPLIERS PVT. LTD.', '', 0, 0),
  ('Kartik Traders Pvt. Ltd.', '', 0, 0),
  ('Aarohi Suppliers', '', 0, 0),
  ('Aashirbad Printing and packeging Pvt Ltd', '', 0, 0),
  ('Aasiya Scrap Suppliers', '', 0, 0),
  ('Adarsh Packaging Industries Pvt. Ltd.', '', 0, 0),
  ('Aditya Paper Plate Udhyog', '', 0, 0),
  ('Alka Suppliers', '', 0, 0),
  ('Alok Paper Plate Udyog', '', 0, 0),
  ('Aman Pressing Udhyog', '', 0, 0),
  ('Aman Scrap Suppliers', '', 0, 0),
  ('Ambe Traders & suppliers', '', 0, 0),
  ('Ankita Trade International', '', 0, 0),
  ('Anushka Suppliers', '', 0, 0),
  ('Arati Fragrance', '', 0, 0),
  ('ARIHANT AUTO CORRUGATION', '', 0, 0),
  ('Asian Thai foods pvt ltd', '', 0, 0),
  ('Avni Ventures Pvt. Ltd.', '', 0, 0),
  ('B H Trading Pvt Ltd', '', 0, 0),
  ('B N K Enterprises', '', 0, 0),
  ('Baba Shyam Traders', '', 0, 0),
  ('BHAGWATI TRADERS & SUPPLIERS', '', 0, 0),
  ('BHAWANI TRADERS & SUPPLIERS', '', 0, 0),
  ('Binay kabadi Pasal & Suppliers', '', 0, 0),
  ('BINOD SUPPLIERS', '', 0, 0),
  ('Bishnu Suppliers', '', 0, 0),
  ('C G AGRO', '', 0, 0),
  ('C G BREWERY (NEPAL) PVT LTD', '', 0, 0),
  ('C G Electronics Pvt Ltd', '', 0, 0),
  ('C G Print & Packaging Pvt. Ltd.', '', 0, 0),
  ('C.G FOOD ENTREPRISES', '', 0, 0),
  ('CG Packaging (Nepal) pvt. Ltd.', '', 0, 0),
  ('Dauda Suppliers', '', 0, 0),
  ('Devchuli Scrap Centre', '', 0, 0),
  ('Dipu Nipu Suppliers Pvt Ltd', '', 0, 0),
  ('Divyan Trade & Suppliers', '', 0, 0),
  ('Divyanshi Traders', '', 0, 0),
  ('DURGA MARUTI SUPPLIER', '', 0, 0),
  ('Durga Pulps Pvt. Ltd.', '', 0, 0),
  ('Fine Pack Packeging', '', 0, 0),
  ('Gahwa Mai Packaging Udhyog', '', 0, 0),
  ('Ganinath Traders & Suppliers', '', 0, 0),
  ('Goshali Packaging Ind. Pvt. Ltd.', '', 0, 0),
  ('Goshali Print & Pack', '', 0, 0),
  ('Gupta Service Pvt. Ltd.', '', 0, 0),
  ('Hanumant Group Pvt. Ltd.', '', 0, 0),
  ('Himal Business Concern', '', 0, 0),
  ('J K Production House', '', 0, 0),
  ('J.K Production House', '', 0, 0),
  ('Jagadamba Printing and Packaging', '', 0, 0),
  ('Jay Balaji Enterprises', '', 0, 0),
  ('Jay Bholebaba Suppliers', '', 0, 0),
  ('JAY BHOLENATH SCRAP CENTRE', '', 0, 0),
  ('Jay Jagadamba Hardware & Suppliers', '', 0, 0),
  ('Jay Jagdamba Packaging', '', 0, 0),
  ('Jay Ma Ambe Catoon Udhyog', '', 0, 0),
  ('Jay Maa Geeta Suppliers', '', 0, 0),
  ('Jay Mahadev Traders', '', 0, 0),
  ('Jay Maruti Suppliers', '', 0, 0),
  ('Jay Mata Di Stores', '', 0, 0),
  ('Jay Mata Di Suppliers', '', 0, 0),
  ('Jay Shiv Bajrang Traders', '', 0, 0),
  ('JAYS SUPPLIERS', '', 0, 0),
  ('K.K. Enterprises', '', 0, 0),
  ('Kabari Stores', '', 0, 0),
  ('Kanti Scrap Kawad', '', 0, 0),
  ('Krishna Paper Janya Bhada Udhyog', '', 0, 0),
  ('Laxmi Scrap Trade & Suppliers', '', 0, 0),
  ('LAXMI WASTAGE SUPPLIERS', '', 0, 0),
  ('M.B. Traders & Suppliers', '', 0, 0),
  ('Ma Ambe Traders', '', 0, 0),
  ('Ma Bhawani Trade & Suppliers', '', 0, 0),
  ('Ma Durga Paper Plate Udhyog', '', 0, 0),
  ('Ma Shanti Scrap Centre', '', 0, 0),
  ('MA Shanti Trade & Suppliers', '', 0, 0),
  ('MA Sita Suppliers', '', 0, 0),
  ('Maa Sonasati Traders', '', 0, 0),
  ('Makalu Soap & Chemical Industries Pvt Ltd', '', 0, 0),
  ('Malashree Suppilers', '', 0, 0),
  ('Manakamana scrap company', '', 0, 0),
  ('Manokamana Kabad Suppliers', '', 0, 0),
  ('MARUTI MATCH', '', 0, 0),
  ('Maruti Print & Pack Pvt. Ltd.', '', 0, 0),
  ('MAYA DEVI SCRAP PVT LTD', '', 0, 0),
  ('MB Scrap Center', '', 0, 0),
  ('N.S. Packeging Pvt Ltd', '', 0, 0),
  ('NAMAN Traders & Suppliers', '', 0, 0),
  ('NAMOBUDHH SUPPLIERS', '', 0, 0),
  ('Nandani Packaging Industries (P.) Ltd.', '', 0, 0),
  ('NAV DURGA TRADERS', '', 0, 0),
  ('NEPAL CARDBOARD INDUSTRIES', '', 0, 0),
  ('NEPAL PRINTING WORKS', '', 0, 0),
  ('NEW KHUSBOO ENTERPRISES', '', 0, 0),
  ('New Khusi Marketing', '', 0, 0),
  ('New Lumbini Pressing Udyog', '', 0, 0),
  ('New Shiv Trade Link', '', 0, 0),
  ('New Shivaya Stores', '', 0, 0),
  ('New Yadav Traders', '', 0, 0),
  ('Niraj Kabadi Suppliers', '', 0, 0),
  ('Noble Packaging Pvt. Ltd.', '', 0, 0),
  ('Noor Suppliers & Traders', '', 0, 0),
  ('OM Jay Shree Traders', '', 0, 0),
  ('OM P Traders', '', 0, 0),
  ('Om Rajdevi Maikwad  Kharid Bikri', '', 0, 0),
  ('Om Shanti Kabadi Suppliers', '', 0, 0),
  ('Om Traders & Suppliers', '', 0, 0),
  ('Omkara Trading Pvt Ltd', '', 0, 0),
  ('P R Trading', '', 0, 0),
  ('PANDAV TRADERS & SUPPLIERS', '', 0, 0),
  ('Pandey Traders', '', 0, 0),
  ('PANNA PAPER  WORKS', '', 0, 0),
  ('Perfect Blends (Nepal) Pvt Ltd', '', 0, 0),
  ('Pooja Enterprises', '', 0, 0),
  ('PRAKASH KAWADI', '', 0, 0),
  ('Pramod Traders', '', 0, 0),
  ('PRINT PAPER CUP INDUSTRIES', '', 0, 0),
  ('PURSOTAM KABAR KAGAJ', '', 0, 0),
  ('R.R Polycating & Lamination industries', '', 0, 0),
  ('Raj Binesh Saroj Traders', '', 0, 0),
  ('RAJA TRADING(LALAN SHAH)', '', 0, 0),
  ('Rajan Traders & Suppliers', '', 0, 0),
  ('RAJLAXMI PRESSING UDHYOG', '', 0, 0),
  ('Ratan Shree Packeging Udhyog Pvt ltd', '', 0, 0),
  ('Raunak International', '', 0, 0),
  ('Roshani Kawadi Suppliers', '', 0, 0),
  ('Rubi Pari Traders', '', 0, 0),
  ('Rubi Traders', '', 0, 0),
  ('S M Kabadi & Suppliers', '', 0, 0),
  ('Sadashiv Silver Paper Tatha Glass Ind.', '', 0, 0),
  ('Sahara Packaging Pvt. Ltd.', '', 0, 0),
  ('Sahara Packging Pvt Ltd', '', 0, 0),
  ('Saipal Suppliers', '', 0, 0),
  ('Sani Traders & Suppliers', '', 0, 0),
  ('Saran Traders', '', 0, 0),
  ('Saraswati Hardware & Suppliers', '', 0, 0),
  ('SATYA SHIV TRADE LINK', '', 0, 0),
  ('Saurabh Foods Products(P.)Ltd.', '', 0, 0),
  ('Scrap Trading', '', 0, 0),
  ('Shah Cartoon Packaging Udhyog', '', 0, 0),
  ('Shiv Cartoon Udgyog', '', 0, 0),
  ('Shiv Cartoon Udhyog', '', 0, 0),
  ('Shiv Packaging Industries', '', 0, 0),
  ('Shiv Scrap Traders', '', 0, 0),
  ('Shiv Suppliers', '', 0, 0),
  ('Shiva Shakti Print & Pack Industries (P.) Ltd', '', 0, 0),
  ('Shivam Traders', '', 0, 0),
  ('Shree Gadhimai Paper Plate Udhyog', '', 0, 0),
  ('Shree Gahwa Mai Pressing', '', 0, 0),
  ('Shree Krishna Paper Janya Bhada Udyog', '', 0, 0),
  ('SHREE LAXMI SCRAP SUPPLIERS', '', 0, 0),
  ('Shree MA Rajdevi Suppliers', '', 0, 0),
  ('Shree New Baba Kabadi', '', 0, 0),
  ('Shree Ramchandra Traders', '', 0, 0),
  ('Shubham Botal Suppliers', '', 0, 0),
  ('Siddhi Binayak Packaging & Printing Ind. Pvt. Ltd.', '', 0, 0),
  ('Siddhi Ganesh & Pathibhara Suppliers', '', 0, 0),
  ('Sri Hanuman', '', 0, 0),
  ('Sri Krishna Paper Janya Bhada Udhyog', '', 0, 0),
  ('Suman Scrap Centre', '', 0, 0),
  ('Sumit & Uttam Suppliers', '', 0, 0),
  ('Super Print & Pack Pvt Ltd', '', 0, 0),
  ('Suraj Chandan', '', 0, 0),
  ('Suraj Suppliers', '', 0, 0),
  ('SURYA SUPPLIERS', '', 0, 0),
  ('Trishakti Traders', '', 0, 0),
  ('Unique Wide International PVT LTD', '', 0, 0),
  ('United Packeging Pvt Ltd', '', 0, 0),
  ('Vishal Store', '', 0, 0),
  ('Vivek Suppliers', '', 0, 0),
  ('Yeti Polychem Pvt Ltd', '', 0, 0),
  ('Bindwashni & Supplier', '', 0, 0),
  ('Britannia Nepal Private Limited', '', 0, -28330.35),
  ('J.P. Trading Home Pvt. Ltd.', '', 0, -241978),
  ('J K Paper Pressing Udhyog Pvt Ltd', '', 0, -750000),
  ('Vaishnavi  Craft Udhyog Pvt. Ltd.', 'Tokha,kathmandu', 23500, 0)
ON CONFLICT (party_name) DO UPDATE SET
  address = EXCLUDED.address,
  freight = EXCLUDED.freight,
  opening = EXCLUDED.opening;