-- TRUCKS
INSERT INTO trucks (truck_number, driver_name, avg_kmpl) VALUES
  ('8596', 'Bashunath',        4.2),
  ('8597', 'Bibek Bista',       4.2),
  ('8598', 'Om Bahadur Gurung', 4.2),
  ('8599', 'Bibek Bista',       4.2),
  ('8600', 'Suman Lama Thokar', 4.2),
  ('0122', 'Madhav Karki',      4.2)
ON CONFLICT (truck_number) DO NOTHING;

-- SOURCES
INSERT INTO sources (name, address, lat, lng) VALUES
  ('Maruti Print & Pack Limited',     'Chorni 44400, Birgunj, Nepal', 27.6710, 85.4298),
  ('Maruti Graphics Limited',         'Chorni 44400, Birgunj, Nepal', 27.6710, 85.4298),
  ('Shree Maruti and Paper Pvt Ltd',  'Chorni 44400, Birgunj, Nepal', 27.6710, 85.4298)
ON CONFLICT (name) DO NOTHING;

-- CUSTOMERS
-- Original seeded customers (with known freight rates) + all new ones from customer list
INSERT INTO customers (name, destination_address, destination_lat, destination_lng, freight_actual, freight_dhuwwani) VALUES
  -- ── Known rate customers (original seed) ──────────────────────────────
  ('AMTECH MED (P.) LTD',                                          'Kathmandu, Nepal',    27.7172, 85.3240,  11000, 14300),
  ('ANTARCTIC BISCUITS PRIVATE LIMITED',                           'Hetauda, Nepal',      27.4286, 85.0317,  11000, 14300),
  ('ASIAN BISCUIT & CONFECTIONERY LTD',                            'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('ASIAN THAI FOODS LTD.',                                        'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('B.H.P. MANUFACTURING PVT.LTD',                                 'Kathmandu, Nepal',    27.7172, 85.3240,   6000,  7800),
  ('BIRAT HEALTHCARE INDUSTRIES PVT. LTD.',                        'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('BOTTLERS NEPAL (TERAI) LIMITED',                               'Bharatpur, Nepal',    27.6833, 84.4333,  18000, 23400),
  ('CHANDIKA DISTILLERY PVT LTD.',                                 'Rangeli, Nepal',      26.4667, 87.4333,  30000, 39000),
  ('CHANDRA SHIV RICE & OIL MILLS PVT LTD',                       'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('DABUR NEPAL PRIVATE LIMITED',                                  'Simra, Nepal',        27.1583, 84.9800,   5500,  7150),
  ('DUGAR EDIBLES PVT LTD',                                        'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('DUGAR SPICES & PRODUCTS PVT LTD',                              'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('GAUSHALA GENERAL STORES',                                      'Mahottari, Nepal',    26.6500, 85.9167,  15000, 19500),
  ('GORKHA BREWERY PVT LTD',                                       'Bharatpur, Nepal',    27.6833, 84.4333,  18000, 23400),
  ('HEALTH AND HYGIENE PRODUCTS PVT LTD',                          'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('HIMALAYAN DISTILLERY LTD',                                     'Kathmandu, Nepal',    27.7172, 85.3240,   5500,  7150),
  ('HIMALI KATTHA UDYOG',                                          'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('HIMSHREE FOODS PVT LTD',                                       'Pokhara, Nepal',      NULL,    NULL,     31000, 40300),
  ('JAGDAMBA SPINNING MILLS LIMITED',                              'Bhairahawa, Nepal',   27.5036, 83.4486,  27000, 35100),
  ('JANAKPUR AGRO FARM LIMITED',                                   'Janakpur, Nepal',     26.7288, 85.9258,  16000, 20800),
  ('JASHN TRADING HOUSE',                                          'Biratnagar, Nepal',   NULL,    NULL,     NULL,  NULL),
  ('JAWALAKHEL DISTILLERY PVT.LTD.',                               'Bhairahawa, Nepal',   27.5036, 83.4486,  27000, 35100),
  ('KAWALITY CHEM PVT LTD',                                        'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('KAWALITY OIL REFINERY PVT LTD',                                'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('KIRITI PRINT AND PACK INDUSTRIES',                             'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('KWALITY DIET AND FOOD PRODUCTS PVT LTD',                       'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('KWALITY FOODS NEPAL PVT LTD',                                  'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('KWALITY NOODLES INDUSTRIES PVT LTD',                           'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('KWALITY THAI FOODS PVT LTD',                                   'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('LAKSHYA POULTRY PVT LTD',                                      'Hetauda, Nepal',      NULL,    NULL,     17000, 22100),
  ('MM PLASTIC UDYOG PVT.LTD.',                                    'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('PASHUPATI PAINTS PVT LTD',                                     'Biratnagar, Nepal',   26.4525, 87.2718,  28000, 36400),
  ('PREMIER DISTILLERY LTD',                                       'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('PRIME CERAMICS PVT. LTD.',                                     'Kathmandu, Nepal',    27.7172, 85.3240,  13000, 16900),
  ('RAJ BREWERY PVT LTD',                                          'Bhairahawa, Nepal',   27.5036, 83.4486,  27000, 35100),
  ('RAM JANAKI TEL REFINE TATHA PACKAGING UDHYOG PVT . LTD',      'Bhairahawa, Nepal',   NULL,    NULL,     17000, 22100),
  ('SARAS BEVERAGES PVT. LTD.',                                    'Kathmandu, Nepal',    NULL,    NULL,     19000, 24700),
  ('SHAKTI KALIKA POULTRY PVT LTD',                                'Hetauda, Nepal',      NULL,    NULL,     17000, 22100),
  ('SHREE DISTILLERY LTD',                                         'Narayanghat, Nepal',  27.7031, 84.3825,  21000, 27300),
  ('SHREE PASHUPATI BISCUITS INDUSTRIES PVT LTD',                  'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('SIDDHARTHA OIL INDUSTRIES',                                    'Bhairahawa, Nepal',   27.5036, 83.4486,  27000, 35100),
  ('SIDDHARTHA PET PLAST INDUSTRIES PVT LTD',                      'Bhairahawa, Nepal',   27.5036, 83.4486,  27000, 35100),
  ('SUNSHINE FOODS PRIVATE LIMITED',                               'Bhairahawa, Nepal',   27.5036, 83.4486,  27000, 35100),
  ('SURYA NEPAL PVT LTD brt',                                      'Biratnagar, Nepal',   26.4525, 87.2718,  27000, 35100),
  ('TIGER BREWERY INDUSTRY PVT LTD',                               'Bhairahawa, Nepal',   27.5036, 83.4486,  28000, 36400),
  ('YAK BREWING COMPANY PVT LTD',                                  'Bharatpur, Nepal',    27.6833, 84.4333,  21000, 27300),
  ('YASHODA FOODS PVT. LTD.',                                      'Bhairahawa, Nepal',   27.5036, 83.4486,  28000, 36400),
  ('SURYA NEPAL PVT LTD',                                          'Simra, Nepal',        27.1583, 84.9800,   5500,  7150),

  -- ── New customers from Excel list (no freight rate yet — to be updated) ──
  ('A.S.T. PVT. LTD',                                             NULL, NULL, NULL, NULL, NULL),
  ('AARTI VEGETABLE PRODUCTS PVT. LTD.',                          NULL, NULL, NULL, NULL, NULL),
  ('ACTION POLYMERS LIMITED',                                     NULL, NULL, NULL, NULL, NULL),
  ('ADITYA INTERNATIONAL',                                        NULL, NULL, NULL, NULL, NULL),
  ('AGRO THAI FOOD PVT LTD',                                      NULL, NULL, NULL, NULL, NULL),
  ('A.M.S DISTIILERY PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('ALLIED STEELS PVT LTD',                                       NULL, NULL, NULL, NULL, NULL),
  ('AMRAPALI BEVERAGE PVT LTD',                                   NULL, NULL, NULL, NULL, NULL),
  ('ANAND PLASTIC LALITPUR PVT LTD',                              NULL, NULL, NULL, NULL, NULL),
  ('ANANDAMI SNACKS & BEVERAGES INTERNATIONAL PRIVATE LIMITED',   NULL, NULL, NULL, NULL, NULL),
  ('ANJANI AND SONS IMPEX PVT LTD',                               NULL, NULL, NULL, NULL, NULL),
  ('ANNAPURNA RATHI CABLES INDUSTRIES PVT.LTD',                  NULL, NULL, NULL, NULL, NULL),
  ('ANNAPURNA POULRY BREEDERS FARM PVT. LTD.',                   NULL, NULL, NULL, NULL, NULL),
  ('ANNAPURNA VEGETABLE PRODUCTS PVT. LTD',                      NULL, NULL, NULL, NULL, NULL),
  ('ARATI FRAGRANCE',                                             NULL, NULL, NULL, NULL, NULL),
  ('ARCHIE LABEL PRINTERS',                                       NULL, NULL, NULL, NULL, NULL),
  ('ASAL HYGIENE PRODUCTS PVT. LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('ASIA CHEM PVT LTD',                                          NULL, NULL, NULL, NULL, NULL),
  ('B TO B HOSPITALITY PVT. LTD.',                               NULL, NULL, NULL, NULL, NULL),
  ('BABA SOAP INDUSTRIES PVT LTD',                               NULL, NULL, NULL, NULL, NULL),
  ('BABA VEGETABLE OIL INDUSTRIES PVT LTD',                      NULL, NULL, NULL, NULL, NULL),
  ('BAGMATI OIL INDUSTRIES',                                     NULL, NULL, NULL, NULL, NULL),
  ('BAKERS FOOD PRODUCTS',                                       NULL, NULL, NULL, NULL, NULL),
  ('BANSHAL ENTERPRISE',                                         NULL, NULL, NULL, NULL, NULL),
  ('BARA FOOD & BEVERAGE PVT. LTD.',                             NULL, NULL, NULL, NULL, NULL),
  ('BARDIYA DISTILLERY PVT.LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('BRITANNIA NEPAL PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('CAPITAL FOODS PVT LTD',                                      NULL, NULL, NULL, NULL, NULL),
  ('CG FOOD (NEPAL) PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('CG OIL & DERIVATIVES PVT LTD',                               NULL, NULL, NULL, NULL, NULL),
  ('CG PRINT AND PACKAGING PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('CLASSIC INDUSTRIES PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('DAUNNE AGRO FARM LTD',                                       NULL, NULL, NULL, NULL, NULL),
  ('DEUTI SOAP AND CHEMICALS PVT LTD.',                          NULL, NULL, NULL, NULL, NULL),
  ('DIPSON FOOD UDYOG COMPANY',                                  NULL, NULL, NULL, NULL, NULL),
  ('DURGA STEEL INDUSTRIES PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('EVEREST PARENTERALS PVT LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('EVEREST PIPE INDUSTRIES',                                    NULL, NULL, NULL, NULL, NULL),
  ('FINE CORRUGATION AND COATING INDUSTRIES',                    NULL, NULL, NULL, NULL, NULL),
  ('FIRST CHOICE FOODS PRIVATE LIMITED',                         NULL, NULL, NULL, NULL, NULL),
  ('FORTUNE STEEL IMPEX PVT LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('FRUIT AGRO PRODUCT PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('GANAPATI VANASPATI PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('GANDAKI OIL MILL PVT LTD',                                   NULL, NULL, NULL, NULL, NULL),
  ('GANPATI PAPER BOX REPARING UDHYOG',                          NULL, NULL, NULL, NULL, NULL),
  ('GLOBAL CARTON UDHYOG(DR)',                                   NULL, NULL, NULL, NULL, NULL),
  ('GOODLIFE BEVERAGES PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('GOODRIDE LUBRICANTS LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('GOVIND OIL INDUSTRIES',                                      NULL, NULL, NULL, NULL, NULL),
  ('GSK VERSATILE',                                              NULL, NULL, NULL, NULL, NULL),
  ('GYAN ENTERPRISES',                                           NULL, NULL, NULL, NULL, NULL),
  ('HILIFE AGRO AND FOODS INDUSTRIES LTD',                       NULL, NULL, NULL, NULL, NULL),
  ('HIM SHREE FOODS WESTERN NEPAL LTD.',                         NULL, NULL, NULL, NULL, NULL),
  ('HIMALI CHEMICAL & PERFUMERY UDHYOG',                         NULL, NULL, NULL, NULL, NULL),
  ('HIMALAYAN BREWERY PVT. LTD.',                                NULL, NULL, NULL, NULL, NULL),
  ('HIMCHULI POULTRY PVT.LTD.',                                  NULL, NULL, NULL, NULL, NULL),
  ('HIMGIRI HYGIENE LTD',                                        NULL, NULL, NULL, NULL, NULL),
  ('HITEX SYNTHETIC PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('HOMTECH INDUSTRIES PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('HUMAN DEVELOPMENT NEPAL',                                    NULL, NULL, NULL, NULL, NULL),
  ('HYGEN PACKS NEPAL PVT LTD',                                  NULL, NULL, NULL, NULL, NULL),
  ('ILAM TEA PRODUCERS PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('INESH GLOBAL PVT.LTD',                                       NULL, NULL, NULL, NULL, NULL),
  ('SARBOTTAM SPINNING MILLS LIMITED',                           NULL, NULL, NULL, NULL, NULL),
  ('JAI SHREE SHYAM KATTHA UDHYOG',                              NULL, NULL, NULL, NULL, NULL),
  ('JAISHREE HEALTHCARE PVT LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('JANAKPUR REFINERIES PVT LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('JAWALAKHEL GROUP OF INDUSTRIES PVT LTD',                     NULL, NULL, NULL, NULL, NULL),
  ('JAY SHREE POLYMERS PVT LTD.',                                NULL, NULL, NULL, NULL, NULL),
  ('KABERI INDUSTRIES PVT LTD',                                  NULL, NULL, NULL, NULL, NULL),
  ('KAJARIA RAMESH TILES LTD',                                   NULL, NULL, NULL, NULL, NULL),
  ('KALASH SOAP INDUSTRIES PVT. LTD.',                           NULL, NULL, NULL, NULL, NULL),
  ('KAMAKHYA BREEDING FARM PVT. LTD',                            NULL, NULL, NULL, NULL, NULL),
  ('KARMACHARYA BAKES AND FOODS PVT.LTD',                        NULL, NULL, NULL, NULL, NULL),
  ('KARNALI DISTILLERY PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('KATHMANDU POULTRY PVT LTD',                                  NULL, NULL, NULL, NULL, NULL),
  ('KHAJURICO NEPAL PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('KHANAL POULTRY PVT LTD',                                     NULL, NULL, NULL, NULL, NULL),
  ('KHILUNG KALIKA AGRO FARM PVT.LTD.',                          NULL, NULL, NULL, NULL, NULL),
  ('GOLDSTAR STRIDE LTD.',                                       NULL, NULL, NULL, NULL, NULL),
  ('KISAN DANA UDHYOG PVT.LTD.',                                 NULL, NULL, NULL, NULL, NULL),
  ('KNP JAPAN PVT. LTD.',                                        NULL, NULL, NULL, NULL, NULL),
  ('KOHINOOR PLASTIC INDUSTRIES PVT LTD',                        NULL, NULL, NULL, NULL, NULL),
  ('KRS VENTURE PVT.LTD.',                                       NULL, NULL, NULL, NULL, NULL),
  ('KWALITY FOOD AND SNACKS INDUSTRIES PVT LTD',                 NULL, NULL, NULL, NULL, NULL),
  ('LAXMI NARAYAN OIL AND REFINERY PVT LTD',                     NULL, NULL, NULL, NULL, NULL),
  ('LAXMI TECHNOPLAST PVT LTD',                                  NULL, NULL, NULL, NULL, NULL),
  ('HIMALAYAN BOTTLERS PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('LIFE FOOD AND BEVERAGE PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('LOKRAJ CARTOON BOX UDHYOG',                                  NULL, NULL, NULL, NULL, NULL),
  ('LUMBINI CERAMICS LIMITED',                                   NULL, NULL, NULL, NULL, NULL),
  ('MAA DURGA FOODS PVT. LTD',                                   NULL, NULL, NULL, NULL, NULL),
  ('MAHALAXMI SOLVENT & REFINERY PVT LTD',                       NULL, NULL, NULL, NULL, NULL),
  ('MAKALU DISTILLERY PVT. LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('MANGALAM INDUSTRIES LIMITED',                                NULL, NULL, NULL, NULL, NULL),
  ('MARUTI GRAPHICS PVT LTD (DEBTORS)',                          NULL, NULL, NULL, NULL, NULL),
  ('MARUTI MATCH INDUSTRIES PVT. LTD',                           NULL, NULL, NULL, NULL, NULL),
  ('MAYUR LAMICOATS PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('MECHI PERFECT GROUP PVT LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('METRI MULTI FARMING',                                        NULL, NULL, NULL, NULL, NULL),
  ('NANDAN GHEE & OIL INDUSTRIES PVT LTD',                       NULL, NULL, NULL, NULL, NULL),
  ('NAPPY & PASTE MATERIAL PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('NARAYANI OIL REFINARY UDHYOG PVT LTD',                       NULL, NULL, NULL, NULL, NULL),
  ('NATRAJ FOOD INDUSTRIES PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('NATIONAL AUTO AND SPRAY UDHYOG',                             NULL, NULL, NULL, NULL, NULL),
  ('NATIONAL PRODUCTION PVT LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('NATRAJ AGRO PVT LTD',                                        NULL, NULL, NULL, NULL, NULL),
  ('NEBICO PRIVATE LIMITED',                                     NULL, NULL, NULL, NULL, NULL),
  ('NEPAL CERAMIC INDUSTRIES PVT LTD',                           NULL, NULL, NULL, NULL, NULL),
  ('NEPAL EVEREST FOODS & SNACKS PVT. LTD.',                     NULL, NULL, NULL, NULL, NULL),
  ('NEPAL PETRO LUBE IND.PVT.LTD.',                              NULL, NULL, NULL, NULL, NULL),
  ('NIP HOLDINGS PVT LTD',                                       NULL, NULL, NULL, NULL, NULL),
  ('NOBLE PACKAGING PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('NOBLE PRINT & PACKAGING IND.PVT LTD',                        NULL, NULL, NULL, NULL, NULL),
  ('OCB FOODS AND FEEDS PVT LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('OCEAN PLASTIC INDUSTRIES.',                                  NULL, NULL, NULL, NULL, NULL),
  ('ODAT BEVERAGE PVT LTD',                                      NULL, NULL, NULL, NULL, NULL),
  ('ODAT FOOD & BEVERAGE PVT.LTD.',                              NULL, NULL, NULL, NULL, NULL),
  ('OMSHREE POULTRY FARM PVT.LTD',                               NULL, NULL, NULL, NULL, NULL),
  ('PACT GROUP CLOSURE SYSTEMS NEPAL PVT. LTD',                  NULL, NULL, NULL, NULL, NULL),
  ('PANNA PAPER WORKS',                                          NULL, NULL, NULL, NULL, NULL),
  ('PASHUPATI KHADYA TELUDHYOG PVT LTD',                         NULL, NULL, NULL, NULL, NULL),
  ('PERFETTI VAN MELLE NEPAL PVT LTD.',                          NULL, NULL, NULL, NULL, NULL),
  ('PLAST CREATION PVT LTD',                                     NULL, NULL, NULL, NULL, NULL),
  ('POSHAK BREEDER FARM PVT.LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('PREMIA FOODS ADDITIVES PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('PRIME CABLE INDUSTRIES PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('PULSE FASHION SOLUTION PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('PURBANCHAL HATCHERY IND.PVT.LTD',                            NULL, NULL, NULL, NULL, NULL),
  ('PURBANCHAL POLUTRY PRIVATE LIMITED',                         NULL, NULL, NULL, NULL, NULL),
  ('PURE FARM PRODUCTS PVT.LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('PURWANCHAL DISTILLERY PVT LTD',                              NULL, NULL, NULL, NULL, NULL),
  ('R. R. POLYCOATING & LAMINATION INDUSTRIES',                  NULL, NULL, NULL, NULL, NULL),
  ('R.K. PLASTIC PVT. LTD.',                                     NULL, NULL, NULL, NULL, NULL),
  ('RADHA KRISHNA HOME APPLIANCES PVT. LTD.',                    NULL, NULL, NULL, NULL, NULL),
  ('RATNASHREE PACKAGING UDHYOG PVT LTD',                        NULL, NULL, NULL, NULL, NULL),
  ('RELIANCE MANUFACTURING COMPANY PVT.LTD.',                    NULL, NULL, NULL, NULL, NULL),
  ('RELIANCE SPINNING MILLS LTD',                                NULL, NULL, NULL, NULL, NULL),
  ('RIJAL FOOD & BEVERAGES PVT.LTD.',                            NULL, NULL, NULL, NULL, NULL),
  ('RMC FOODS PVT LTD',                                          NULL, NULL, NULL, NULL, NULL),
  ('ROHIT INTERNATIONAL',                                        NULL, NULL, NULL, NULL, NULL),
  ('SACHI JELLY UDYOG',                                          NULL, NULL, NULL, NULL, NULL),
  ('SAFE SOLUTION NEPAL',                                        NULL, NULL, NULL, NULL, NULL),
  ('SAGAR DISTILLERIES PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('SAI SHREE FOODS PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('SALASAR BALAJI OIL INDUSTRIES PVT LTD',                      NULL, NULL, NULL, NULL, NULL),
  ('SANCHETI AGGRO INDUSTRIES PVT LTD',                          NULL, NULL, NULL, NULL, NULL),
  ('SATKOSHI POLUTRY FARM PVT.LTD.',                             NULL, NULL, NULL, NULL, NULL),
  ('SAUMYA INVESTMENTS PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('SAURABH FOOD PRODUCTS PVT LTD',                              NULL, NULL, NULL, NULL, NULL),
  ('SAURABH OIL AND AGRO INDUSTRIES',                            NULL, NULL, NULL, NULL, NULL),
  ('SHREE GANPATI AGRICULTURE FARM PVT LTD',                     NULL, NULL, NULL, NULL, NULL),
  ('SHREE KRISHNA OIL REF. & VEG. GHEE IND. PVT. LTD.',         NULL, NULL, NULL, NULL, NULL),
  ('SHREE MARUTI PAPER & CHEMICAL INDUSTRIES LTD (DEBTOR)',       NULL, NULL, NULL, NULL, NULL),
  ('SHREE PASHUPATI SPICE AND FOOD REPACKING',                   NULL, NULL, NULL, NULL, NULL),
  ('SHREE RAM REFINE OIL PRODUCTS PVT LTD',                      NULL, NULL, NULL, NULL, NULL),
  ('SHREE SHIV SHAKTI GHEE UDYOG PVT LTD',                       NULL, NULL, NULL, NULL, NULL),
  ('SHREYA INDUSTRIES',                                          NULL, NULL, NULL, NULL, NULL),
  ('SIDDHARTHA REFINERY AND SOLVENT INDUSTRY PVT LTD',           NULL, NULL, NULL, NULL, NULL),
  ('SIDDHIVINAYAK OILS PVT. LTD.',                               NULL, NULL, NULL, NULL, NULL),
  ('SOFTY HYGIENE PVT LTD',                                      NULL, NULL, NULL, NULL, NULL),
  ('SOFTY PAPER INDUSTRY PVT.LTD.',                              NULL, NULL, NULL, NULL, NULL),
  ('SOUTH ASIAN BEVERAGES PVT LTD',                              NULL, NULL, NULL, NULL, NULL),
  ('SPM PRINTERS PRIVATE LIMITED',                               NULL, NULL, NULL, NULL, NULL),
  ('STAREX PLASTIC INDUSTRIES',                                  NULL, NULL, NULL, NULL, NULL),
  ('SUBIS POLUTRY PRIVATE LIMITED',                              NULL, NULL, NULL, NULL, NULL),
  ('SUDUR FOOD INDUSTRIES',                                      NULL, NULL, NULL, NULL, NULL),
  ('SUJAL FOOD PVT LTD',                                         NULL, NULL, NULL, NULL, NULL),
  ('SUNRISE CONTAINER PVT LTD',                                  NULL, NULL, NULL, NULL, NULL),
  ('SUNRISE LIQUOR PVT.LTD.',                                    NULL, NULL, NULL, NULL, NULL),
  ('SUPER QUALITY MEAT PROCESSING INDUSTRY PVT. LTD',            NULL, NULL, NULL, NULL, NULL),
  ('SURYA NEPAL VENTURES PVT LTD',                               NULL, NULL, NULL, NULL, NULL),
  ('SUSHIL VANASPATI PVT LTD',                                   NULL, NULL, NULL, NULL, NULL),
  ('SWASTIK INDUSTRIES',                                         NULL, NULL, NULL, NULL, NULL),
  ('SWASTIK OIL INDUSTRIES PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('TEN PLAST INDUSTRIES',                                       NULL, NULL, NULL, NULL, NULL),
  ('TONG GARDEN PRIVATE LIMITED',                                NULL, NULL, NULL, NULL, NULL),
  ('TRISHUL ANCILLARY PRODUCTS AND PACKAGING PVT LTD',           NULL, NULL, NULL, NULL, NULL),
  ('TRIVENI SYNTHETIC YARN IND.PVT.LTD',                         NULL, NULL, NULL, NULL, NULL),
  ('TULASI MOTOR PUMP INDUSTRY PVT LTD',                         NULL, NULL, NULL, NULL, NULL),
  ('UNILEVER NEPAL LTD',                                         NULL, NULL, NULL, NULL, NULL),
  ('UNITED PACKAGING PRIVATE LIMITED',                           NULL, NULL, NULL, NULL, NULL),
  ('VIKAS FOOD PRODUCT PVT.LTD.',                                NULL, NULL, NULL, NULL, NULL),
  ('VIVEK AUTOMOBILES PVT. LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('WINTIME INDUSTRIES PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('YAK BIERGARTEN PVT. LTD.',                                   NULL, NULL, NULL, NULL, NULL),
  ('YETI BREWERY LTD.',                                          NULL, NULL, NULL, NULL, NULL),
  ('YETI DISTILLERY PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('WEGA ELECTRONIC APPLIANCES',                                 NULL, NULL, NULL, NULL, NULL),
  ('SHYDN INDUSTRIES PVT.LTD',                                   NULL, NULL, NULL, NULL, NULL),
  ('SHRINKHALA FOOD AND OIL PROCESSING INDUSTRIES PVT.LTD.',     NULL, NULL, NULL, NULL, NULL),
  ('HIMALAYA FOOD MANUFACTURING PVT. LTD',                       NULL, NULL, NULL, NULL, NULL),
  ('BERGER JENSON & NICHOLSON(NEPAL) PVT LTD',                   NULL, NULL, NULL, NULL, NULL),
  ('MODEL POULTRY UDDHOUGE PVT LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('MARUTI OIL INDUSTRIES PVT LTD',                              NULL, NULL, NULL, NULL, NULL),
  ('OMKAR OIL AND AGRO PACKAGING INDUSTRIES PVT LTD',            NULL, NULL, NULL, NULL, NULL),
  ('SATYAM TECHNO PACK PVT LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('DV FOODS PVT. LTD.',                                         NULL, NULL, NULL, NULL, NULL),
  ('H.O.F. FOODS PVT. LTD.',                                     NULL, NULL, NULL, NULL, NULL),
  ('DAUNNE TRAY & PACKAGING INDUSTRIES PVT. LTD.',               NULL, NULL, NULL, NULL, NULL),
  ('CHACHAN COMMODITIES',                                        NULL, NULL, NULL, NULL, NULL),
  ('WEGA DIGITRONICS PVT LTD',                                   NULL, NULL, NULL, NULL, NULL),
  ('BHERI DISTILLERY AND ALLIED INDUSTRIES PVT LTD',             NULL, NULL, NULL, NULL, NULL),
  ('EVEREST SOLVENT PVT LTD',                                    NULL, NULL, NULL, NULL, NULL),
  ('JAGDAMBA FOODS PVT LTD',                                     NULL, NULL, NULL, NULL, NULL),
  ('SWARNIM AGRO INDUSTRIES PVT LTD',                            NULL, NULL, NULL, NULL, NULL),
  ('MAINALI INDUSTRIES PVT. LTD.',                               NULL, NULL, NULL, NULL, NULL),
  ('SANWARIYA FOODS AND SNACKS PVT. LTD.',                       NULL, NULL, NULL, NULL, NULL),
  ('YASH TRADE LINK',                                            NULL, NULL, NULL, NULL, NULL),
  ('UNIVERSAL RE-PROCESS PVT.LTD.',                              NULL, NULL, NULL, NULL, NULL),
  ('MOUNT EVEREST DISTILLERY LTD.',                              NULL, NULL, NULL, NULL, NULL),
  ('NEPAL PULP AND PAPER INDUSTRIES PVT. LTD.',                  NULL, NULL, NULL, NULL, NULL),
  ('GLOBAL PACKAGING INDUSTRIES PVT. LTD.',                      NULL, NULL, NULL, NULL, NULL),
  ('R L CORP NEPAL PVT. LTD.',                                   NULL, NULL, NULL, NULL, NULL),
  ('JAY MAA TARA DIGITAL PVT. LTD.',                             NULL, NULL, NULL, NULL, NULL),
  ('BLOOMMS AND BEANS PVT. LTD',                                 NULL, NULL, NULL, NULL, NULL),
  ('MORAL TRADING CONCERN PVT.LTD',                              NULL, NULL, NULL, NULL, NULL),
  ('TITAN TEA INDUSTRIES',                                       NULL, NULL, NULL, NULL, NULL),
  ('MANARAM HIMALAYAN HANDICRAFT PVT. LTD.',                     NULL, NULL, NULL, NULL, NULL),
  ('PITAMBARI PRODUCTS PVT. LTD.',                               NULL, NULL, NULL, NULL, NULL),
  ('INTER TECH PIPES AND FITTINGS',                              NULL, NULL, NULL, NULL, NULL),
  ('PASHUPATI KATTHA MILLS PVT.LTD',                             NULL, NULL, NULL, NULL, NULL),
  ('SHREE PARIKRAMA TRADING',                                    NULL, NULL, NULL, NULL, NULL),
  ('DERMSHILED NEPAL SOLUTION',                                  NULL, NULL, NULL, NULL, NULL),
  ('J.K. COMPOSITES NEPAL PVT. LTD.',                            NULL, NULL, NULL, NULL, NULL),
  ('KESHAV COPY UDHYOG',                                         NULL, NULL, NULL, NULL, NULL),
  ('FRUIT AND PAY EXIM PVT. LTD.',                               NULL, NULL, NULL, NULL, NULL),
  ('RANISATI PAPER PRODUCTS',                                    NULL, NULL, NULL, NULL, NULL),
  ('APOLLO PAPER STATIONERY UDHYOG',                             NULL, NULL, NULL, NULL, NULL),
  ('HUMAN RELIEF NEPAL',                                         NULL, NULL, NULL, NULL, NULL),
  ('RAVI INTERCONTINENTAL PVT. LTD.',                            NULL, NULL, NULL, NULL, NULL),
  ('ATLAS PACKAGING INDUSTRIES PVT LTD',                         NULL, NULL, NULL, NULL, NULL),
  ('BALAJEE MANUFACTURING PVT. LTD.',                            NULL, NULL, NULL, NULL, NULL),
  ('ARVIND PULP & PAPER MILLS LTD',                              NULL, NULL, NULL, NULL, NULL),
  ('PAPERLINE ENTERPRISES',                                      NULL, NULL, NULL, NULL, NULL),
  ('SERVOMAX ENGINEERING WORKS',                                 NULL, NULL, NULL, NULL, NULL),
  ('MARUTI PAPER TRADERS',                                       NULL, NULL, NULL, NULL, NULL),
  ('RAM JANAKI TEL REFINE TATHA PACKAGING UDHYOG PVT. LTD',      NULL, NULL, NULL, NULL, NULL),
  ('EVEREST MED PVT. LTD.',                                      NULL, NULL, NULL, NULL, NULL),
  ('PASHUPATI ELECTRIC INDUSTRIES PVT LTD',                      NULL, NULL, NULL, NULL, NULL),
  ('ZIPENG ZHAO',                                                NULL, NULL, NULL, NULL, NULL),
  ('WRITING STUDIO PRIVATE LIMITED',                             NULL, NULL, NULL, NULL, NULL),
  ('RIYAZ TRADERS PVT. LTD',                                     NULL, NULL, NULL, NULL, NULL),
  ('ACCENT EXPORTS PVT LTD.',                                    NULL, NULL, NULL, NULL, NULL),
  ('HIMALAYAN BREWERY PVT. LTD.',                                NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (name) DO NOTHING;

-- BACKLOADS
INSERT INTO backloads (description) VALUES
  ('Scrap from Shree Ramchandra Traders Bhairahawa'),
  ('Scrap from Aarush & Abhishree Suppliers'),
  ('Duplex from Arvind Pulp'),
  ('Duplex from Arvind Pulp for Maruti Graphics & MPP'),
  ('Duplex from Arvind Pulp for MPP & Nepal Print'),
  ('Scrap from Hariom Suppliers'),
  ('Scrap from Yeti Distillery Narayanghat'),
  ('Scrap from Chandrika Distillery Rangeli'),
  ('Scrap from Ram Ram Suppliers Pokhara'),
  ('Scrap from Navdurga Pressing'),
  ('Scrap Loaded from Jay Bholenath Traders'),
  ('Scrap Loaded from Krishna Sah Traders'),
  ('Scrap Loaded from Laxmi Ganesh Traders'),
  ('Scrap Loaded from New Shree Ram Chandra Traders'),
  ('Scrap Loaded from Ram Chandra Traders'),
  ('Scrap Loaded from Ram Ram Suppliers'),
  ('Scrap Loaded from Hariom Suppliers'),
  ('Scrap Loaded from Shivam Packaging'),
  ('Scrap Loaded from Jaiswal Traders Gaur'),
  ('Duplex from Arbind Pulp Mills'),
  ('Return Goods from Vikas Food & Saurabh Oil'),
  ('No Backload')
ON CONFLICT (description) DO NOTHING;